version: '3'
services:
  go:
    build: .
    tty: true
    volumes:
      - .:/app
    ports:
      - 8081:8081
    environment:
      - PMA_HOST=mysql_srv:3307
    depends_on:
      - "db"
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user
      MYSQL_USER: usr
      MYSQL_PASSWORD: password
      MYSQL_TCP_PORT: 3307
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql-data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3307:3306
    expose:
      - 3307
volumes:
  mysql-data:
    driver: local
